---
name: ShopUI
version: 5.0.5
main: AlexPads\CustomShopUI\Main
api: 5.0.0
commands:
 shop:
  description: Opens the ShopUI
  usage: "/shop"
  permission: shop.shop
permissions:
 shop.shop:
  default: true
  description: "Allows user to open the shop using the /shop command"
...
